communitiesuk/funding-service-design-assessment

- README.md
- app/assess/templates/components/applications_table.html
- app/static/src/js/components/filtered-fetch-table/filtered-fetch-table.js
- Classname added to application links on assessment landing page to enable selection by e2e checks
- README note added to highlight that this repo currently has a custom (not templated workflow)
> [No Ticket] E2E classname & readme update

- manifest.yml
Add custom domain for shared cookie
> FS-1050: add custom domain

- Dockerfile
- app/assess/templates/question.html
Updating the dockerfile to work for this app
> Bau fix dockerfile

- .github/workflows/govcloud.yml
- .gitignore
- Dockerfile
- app/assess/data.py
- app/assess/models/application.py
- app/assess/routes.py
- app/assess/templates/question.html
- config/envs/default.py
- config/envs/dev.py
- config/envs/development.py
- config/envs/unit_test.py
- manifest.yml
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/api_data/endpoint_data.json
Updated to use common config class in fsd_utils for shared config values.
Also updated to use `funds/id/rounds` url for retrieving rounds.
> Fs 1169 common config

- .github/dependabot.yml
- .github/workflows/govcloud.yml
- requirements-dev.in
- requirements-dev.txt
https://digital.dclg.gov.uk/jira/browse/FS-1530
> Fs 1530 enable dependabot

- .github/dependabot.yml
- .github/workflows/govcloud.yml
- app/assess/models/application.py
- config/__init__.py
- config/envs/development.py
- requirements-dev.in
- requirements-dev.txt
Added null check around date_submitted from application
> Bau check for null

- app/assess/data.py
- app/assess/models/fund.py
- app/assess/models/round.py
- app/assess/routes.py
- app/assess/templates/components/application_overviews_table.html
- app/assess/templates/components/applications_table.html
- app/assess/templates/landing.html
- app/assess/views/assess.py
- app/assess/views/filters.py
- app/create_app.py
- app/static/src/styles/landing.css
- app/templates/head.html
- build.py
- config/envs/default.py
- config/envs/development.py
- config/envs/unit_test.py
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/api_data/endpoint_data.json
- tests/route_testing_conf.py
- tests/test_accessibility.py
- tests/test_content.py
- tests/test_data.py
- tests/test_data_operations.py
- tests/test_filters.py
- tests/test_initialisation.py
Assessor dashboard to match prototype: https://fsd-funding-prototype-v2.herokuapp.com/s24-assessment/general-assessor-dashboard
As per ticket, search/filter and % complete not included yet.
https://digital.dclg.gov.uk/jira/browse/FS-1573
Includes changes to test data to match what's now in the fund_store.
Have commented out tests around the assessment form screens as I expect they will change over the next few weeks. Marked with TODO in code.
> Fs 1573 - Assessor Dashboard

- README.md
- app/assess/routes.py
- app/assess/templates/components/application_overviews_table.html
- app/assess/templates/landing.html
- app/static/src/styles/landing.css
- requirements-dev.in
- requirements-dev.txt
- tasks.py
- tests/api_data/endpoint_data.json
- tests/test_routes.py
Added clear filters button as per current prototype and discussions with Emma.
It only appears when searching/filtering is applied.
https://fsd-pre-award.herokuapp.com/s26-assessment/search-filtering
> Add clear filters

- app/assess/data.py
- app/assess/routes.py
- app/assess/templates/sub_criteria.html
- app/assess/views/filters.py
- app/create_app.py
- app/static/src/styles/comments.css
- app/templates/head.html
- build.py
- config/envs/default.py
- tests/api_data/endpoint_data.json
- tests/test_data_operations.py
- tests/test_filters.py
Adding comment summary for sub criteria
> Adding comment summary

- .github/workflows/govcloud.yml
Adding step to workflow to call `run-shared-tests.yml` from the shared workflows
> Fs 1972 run shared tests

- app/assess/models/assessor_task_list.py
- app/assess/models/sub_criteria.py
- app/assess/templates/application-section.html
- app/assess/templates/sub_criteria.html
- app/assess/views/filters.py
- app/create_app.py
- tests/api_data/endpoint_data.json
- tests/test_filters.py
Adding method to format the short id to get the project reference
> FIxing project reference

- app/assess/templates/components/application_overviews_table.html
- tests/api_data/endpoint_data.json
Asset type and status columns should now be populating as expected
> Fix for asset and status

- app/assess/models/ui/applicants_response.py
- app/assess/routes.py
- tests/test_applicators_response.py
- tests/test_jinja_macros.py
- Add doc-strings to methods & change terminology to be consistent throughout app
- Handle one unaccounted for use-case where grouped_fields has empty, None or missing answers
> FS-1987: Add doc-strings for applicants response

- app/assess/templates/macros/criteria_element.html
- app/assess/views/filters.py
- tests/test_filters.py
- tests/test_jinja_macros.py
- Remove theme count to match latest prototype
- https://fsd-pre-award.herokuapp.com/s26-assessment/assessment-overview
- Change "Score" to "Score out of 5" to match latest prototype
- Other minor changes
Other relevant JIRAs: [FS-2106](https://digital.dclg.gov.uk/jira/browse/FS-2106) [FS-2105](https://digital.dclg.gov.uk/jira/browse/FS-2105) [FS-1942](https://digital.dclg.gov.uk/jira/browse/FS-1942)
> FS-2000: Dynamically pull score & status from database (front-end)

- app/assess/templates/macros/scores_justification.html
Updated href for assessment guidance on the scoring page
> Adding link for assessment criteria

- app/assess/data.py
- app/assess/routes.py
- app/assess/templates/macros/comments_box.html
- app/assess/templates/sub_criteria.html
- config/envs/default.py
- tests/test_jinja_macros.py
- Can submit comments to assessment store
- Front end UI created for comments form, hidden on initial load, after clicking newly created Add a comment button, comment form with save button is displayed
- theme_id is added to args so the page stays on the current theme after clicking save
> Comments functionality completed

- .github/workflows/govcloud.yml
- app/create_app.py
- manifest.yml
Add Sentry integration as-per other apps.
> BAU: add sentry integration

- app/assess/routes.py
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/macros/comments.html
- app/assess/templates/macros/comments_summary.html
- app/assess/templates/macros/criteria_element.html
- app/assess/templates/macros/sub_criteria_navbar.html
- app/assess/templates/sub_criteria.html
- app/create_app.py
- app/default/routes.py
- app/static/src/scss/navbar.scss
- app/templates/index.html
- config/envs/development.py
- tests/api_data/endpoint_data.json
- tests/route_testing_conf.py
- tests/test_authorisation.py
- tests/test_jinja_macros.py
- tests/test_routes.py
- Return 404 from sub criteria page when thene_id=score and user is not Assessor or Lead Assessor
- Add conditional logic to remove total scores and scores columns from tasklist view for Commenters
- Add conditional logic to remove Score the criteria link from sub-criteria navbar for Commenters
- Add Flask g variable to global template constants for easy use within templates
- Add tests to check above Commenter functionality
- Updated default DEBUG_USER_ROLE to LEAD_ASSESSOR so that full functionality is visible in development by default
Also small fix to add int filter to state.funding_amount_requested formatter in assessor_tasklist.html to ensure correct data type is passed to numeric format function
> FS-2103 Secure commenter routes

- app/static/src/scss/navbar.scss
Navbar was calling a colour that doesn't exist
> Fixing navbar exception

- app/assess/routes.py
- After submitting a comment, we return a redirect to the route so it re-fetches the comments
> FS-2119: Redirect after comment creation

- app/assess/templates/macros/comments_box.html
Change happened after merge, tests are now fixed
> fixing failing test

- app/assess/routes.py
- app/assess/views/filters.py
- Tiny change to override status as "Flagged" when an application has a flag
> BAU: Show application status as Flagged when flag exists

- app/assess/templates/assessor_tasklist.html
Changing scored section title from "Score the application" to "Scored" as per prototype
> Changing Scored section title

- app/assess/templates/components/application_overviews_table.html
Removing location column for launch - will add later as part of FS-2111
> Removing location column for launch

- app/assess/data.py
- app/assess/models/ui/applicants_response.py
- app/assess/routes.py
- tests/test_applicators_response.py
- tests/test_authorisation.py
- tests/test_routes.py
Work around for the pre signed url not downloading the file on uat
> Fix for file downloads

- app/assess/templates/assessor_dashboard.html
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/flag_application.html
- app/assess/templates/macros/logout_partial.html
- app/assess/templates/sub_criteria.html
- Also fix styling on assessor dashboard/tasklist
**Some videos showing styling changes:**
Before:
https://user-images.githubusercontent.com/117724519/211521857-deb23b2b-12db-4a98-bc10-3330d06fbb90.mp4
After: (just showing styling)
https://user-images.githubusercontent.com/117724519/211521481-9a991cd8-e0d5-48ca-beef-408fea0bf15d.mp4
> FS-2143: Add "Log out" option to "Flag application" page

- app/assess/routes.py
- tests/api_data/endpoint_data.json
- tests/test_authorisation.py
Bug fix 🐛 
Flag application—Assessors are unable to flag applications
> Fs 2142 fix flagging auth

- app/assess/templates/components/application_overviews_table.html
- Show Flagged on assessor team dashboard
- Fix filters for Flagged applications, and unhandled statuses
See: https://github.com/communitiesuk/funding-service-design-assessment-store/pull/99
Video demo:
https://user-images.githubusercontent.com/117724519/211817718-967fc98f-c10a-429a-b416-9454f080ae84.mp4
> FS-2149: Show Flagged & fix filters

- app/assess/data.py
- app/assess/routes.py
- tests/test_initialisation.py
- Start posting data as a json body as opposed to query params
Fixes: https://sentry.io/organizations/funding-service-design-team-dl/issues/3850987122/?referrer=slack
> BAU: Change progress endpoint to post

- app/assess/templates/components/application_overviews_table.html
- app/assess/templates/macros/scores.html
Adding aria labels for accessibility issues
> Fs 2164, Fs 2164 aria labels

- app/assess/templates/macros/justification.html
Fixing the axe error for no label on justification
> FS-2166 Fixing axe error for justification 

- app/assess/data.py
Fixing bug that stopped downloading of files when the name had commas in them.
> Fix for commas in file names

- app/assess/templates/assessor_tasklist.html
- app/assess/templates/macros/banner_summary.html
- app/assess/views/filters.py
- app/static/src/styles/govuk-overrides.css
- The assessment status is labeled "Assessment Complete" on the tasklist banner if the assessment has been completed.
- CSS has been added for the "Assessment Complete" prompt.
> FS-2210-confirmation-banner-and-status-to-match-prototype

- app/assess/routes.py
Added fund name to the banner when assessment is completed
> FS-2216-bug-fix-fund-name-appears-none-on-tasklist-banner

- app/assess/templates/continue_assessment.html
- app/assess/templates/macros/banner_summary.html
Continue assessment - Fix margin
https://digital.dclg.gov.uk/jira/browse/FS-2224
Continue assessment - Wrong status in Continue assessment page
https://digital.dclg.gov.uk/jira/browse/FS-2225
> fixes implemented

- app/assess/routes.py
- app/assess/templates/continue_assessment.html
- app/assess/templates/flag_application.html
- app/assess/templates/macros/banner_summary.html
- app/assess/templates/resolve_flag.html
- tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2221
Resolve flag - Wrong status in Resolve flag page
> Fs 2221 resolve flag page status

- app/assess/data.py
- app/assess/helpers.py
- app/assess/models/banner.py
- app/assess/models/round.py
- app/assess/routes.py
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/components/application_overviews_table.html
- app/assess/templates/continue_assessment.html
- app/assess/templates/macros/banner_summary.html
- app/assess/templates/macros/criteria_element.html
- app/assess/templates/resolve_flag.html
- app/assess/templates/sub_criteria.html
- app/assess/views/filters.py
- app/create_app.py
- tests/conftest.py
- tests/test_authorisation.py
- tests/test_filters.py
- tests/test_jinja_macros.py
- tests/test_routes.py
Separate helpers and filter tests, add dataclass for banner, fix tests
> separate helpers and filter tests, add dataclass for banner, fix tests

- app/assess/data.py
- app/assess/routes.py
- app/assess/templates/macros/banner_summary.html
In the tasklist page, the status for "Assessment complete" is being returned as None (only on POST to complete application)
> Fs 2243 assessment complete status

- .github/workflows/s3-zip.yaml
Run action on merge to pick up workflow changes from communitiesuk/funding-service-design-workflows#34
> FS-2172: run tag task on merge

- app/assess/templates/components/application_overviews_table.html
- app/assess/templates/macros/criteria_element.html
- app/assess/templates/macros/section_element.html
Subcriteria status will now be labeled as "Complete" when the status is set to "Completed".
> FS-2245-sub-criteria-status-display

- app/assess/templates/resolve_flag.html
Cancel button bug fix when validation error triggered
> FS-2248-bug-fix-resolve-flag-page-cancel-button

- app/assess/display_value_mappings.py
- app/assess/routes.py
Fix filter search on status or flag
https://digital.dclg.gov.uk/jira/browse/FS-2259
https://digital.dclg.gov.uk/jira/browse/FS-2249
https://digital.dclg.gov.uk/jira/browse/FS-2250
https://digital.dclg.gov.uk/jira/browse/FS-2246
> Fix filter search on status or flag

- app/assess/display_value_mappings.py
https://digital.dclg.gov.uk/jira/browse/FS-2290
> update asset type list

- .github/workflows/govcloud.yml
https://digital.dclg.gov.uk/jira/browse/FS-1200
Added assessment store url to enable performance tests for Assessment store.
N/A
N/A
> FS-1200: Enable performance tests for Assessment store to run in the pipelines 

- app/assess/data.py
This PR fixes the bug when assessor/Lead assessor wants to score a sub criteria for the first time it returns 500 internal server error.
> FS-2561-bug-fix-when-scoring-subcriteria-for-first-time

- requirements-dev.txt
- requirements.in
- requirements.txt
This PR is to update the service with the latest utils
> bau-install-latest-utils-version

- app/create_app.py
- config/envs/default.py
JIRA link
https://digital.dclg.gov.uk/jira/browse/FS-2587
Fixed the page flickering by enabling the caching only on static assets.
Just click on any link & notice the disappeared page flickering.
> enable caching for static assets

- app/assess/data.py
- app/assess/models/ui/applicants_response.py
- app/assess/routes.py
- app/assess/templates/macros/banner_summary.html
- app/assess/templates/macros/justification.html
- app/assess/templates/macros/theme.html
- app/assess/templates/macros/theme/question_above_href_answer_list.jinja2
- config/envs/development.py
- tests/test_applicators_response.py
- tests/test_data.py
- tests/test_jinja_macros.py
Note: Evolved from https://github.com/communitiesuk/funding-service-design-assessment-store/pull/155 & https://github.com/communitiesuk/funding-service-design-assessment/pull/215
Relates to: https://github.com/communitiesuk/funding-service-design-assessment-store/pull/169
- Add new macro for client-side upload rendering
- Support multiple files rendering on the UI
- Refactor existing test coverage to use bs4
- Add test coverage
> BAU: Rendering files from client-side upload

- app/assess/templates/macros/comments_summary.html
[[_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
](https://digital.dclg.gov.uk/jira/browse/FS-2688)
Fixed the position of comments summary box
> fix comments box position

- .vscode/launch.json
- app/assess/models/fund_summary.py
https://digital.dclg.gov.uk/jira/browse/FS-2744
Only shows closed rounds in assessment
> only show closed rounds in assessment

- app/assess/routes.py
- app/assess/templates/flag_application.html
- app/assess/templates/macros/assessment_flag.html
- tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2780
Bug fixes for previously raised PR https://github.com/communitiesuk/funding-service-design-assessment/pull/256
> Fs 2780 flag for multiple sections 2

- app/assess/templates/flag_application.html
https://digital.dclg.gov.uk/jira/browse/FS-2780
Bug fixes for previously raised PR https://github.com/communitiesuk/funding-service-design-assessment/pull/256
> fix accesibility issue checkboxes

- app/assess/data.py
- app/assess/helpers.py
- app/assess/routes.py
- app/assess/templates/flag_application.html
- app/assess/templates/macros/assessment_flag.html
- app/assess/templates/resolve_flag.html
- config/envs/default.py
- tests/api_data/test_data.py
- tests/conftest.py
- tests/test_authorisation.py
- tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2779
Show flagged sections in resolve flag page
Fixed error box for multiple section flagging checkboxes
> Fs 2779 resolve a flag1

- app/assess/models/ui/applicants_response.py
Quickly fixing this bug for release.
Key was changed on accident during a merge conflict resolution.
> BAU: Fix add another key

- app/assess/models/ui/applicants_response.py
replacing dashes with spaces when presenting radiofield answers on assessment.
> fs-3046-display-radio-field-fix

- app/assess/auth/validation.py
- config/envs/default.py
- manifest.yml
- Add 2 environment variables to disable fund specific access & devolved authority auth
> BAU: Disable devolved authority and fund specific access env var

- app/assess/auth/validation.py
- Add an all roles access controller when we're forcing all funds as accessible
> BAU: Allow all access when forcing funds accessible

- app/assess/data.py
- config/envs/development.py
- fix bulk bulk accounts stuff
- remove Todo code (flag history)
> fix debug role settings

- manifest.yml
... Disable funds accessible & devolved auth on test
> BAU: Disable funds accessible & devolved auth on test

- app/assess/data.py
- app/assess/forms/flag_form.py
- app/assess/helpers.py
- app/assess/models/flag.py
- app/assess/models/flag_v2.py
- app/assess/routes.py
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/components/application_overviews_table_cof.html
- app/assess/templates/components/application_overviews_table_nstf.html
- app/assess/templates/components/header.html
- app/assess/templates/flag_application.html
- app/assess/templates/macros/assessment_completion.html
- app/assess/templates/macros/assessment_flag.html
- app/assess/templates/macros/banner_summary.html
- app/assess/templates/macros/flag_history.html
- app/assess/templates/sub_criteria.html
- config/envs/default.py
- config/envs/development.py
- pytest.ini
https://dluhcdigital.atlassian.net/browse/FS-3057
- Added flag v2 endpoint
- Refactored routes.py & data.py to use latest flag_v2 endpoint
- Removed usage of old flag api usage in routes & data.py
- updated Html pages to use flags v2
- Disabled certain unit tests (Need to update tests for flag_v2 which is not part of this task)
- This PR unblocks other flagging tasks
linked PR in assessment store https://github.com/communitiesuk/funding-service-design-assessment-store/pull/208
> Use flag v2 for nsr2 cofr3w1

- app/assess/data.py
- app/assess/templates/macros/assessment_completion.html
- app/assess/templates/macros/qa_complete_flag.html
https://dluhcdigital.atlassian.net/browse/FS-3069
`is_lead_assessor` doesn't exist, we need to check `g.access_controller.is_lead_assessor` to fix the regression
> FS-3069: Lead assessor export data

- app/assess/models/ui/assessor_task_list.py
- app/assess/routes.py
- app/assess/templates/assessor_tasklist.html
Starting work on tagging, addressed a TODO to deduplicate some stuff. Wanted to get it in as a small PR now before all the tagging stuff, easier to merge this way.
Load the assessment tasklist - if the blue banner renders ok then all is well.
N/A
> Refactor building assessor tasklist state

- app/assess/models/ui/assessor_task_list.py
- app/assess/routes.py
- app/assess/templates/components/header.html
Fixing issues in previous PR to refactor the state
Ensure you can flag and score an application
> fixing last change to retrieving the state

- app/assess/auth/validation.py
- config/envs/default.py
- manifest.yml
This code was used temporarily to force the funds open and disable devolved authority auth, just removing it now.
> BAU: Remove force environment variables

- app/assess/helpers.py
- app/assess/routes.py
- app/assess/templates/assessor_tasklist.html
PR to fix QA_Completed banner display
> fix qa_complete banner display

- app/assess/templates/macros/flag_history.html
Dont display qa_complete in flag history
> Dont display qa_complete in flag history

- app/assess/templates/assessor_tasklist.html
- tests/test_routes.py
> fix flag banners display

- app/assess/templates/macros/assessment_flag.html
- tests/test_jinja_macros.py
fix bug - doesnt show reason for flagging
> bau - bugfix show reason for flagging

- app/assess/models/flag_v2.py
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/macros/flag_history.html
https://dluhcdigital.atlassian.net/browse/FS-3135
fix qa_complete returns 500 bug
> bau: fix qa_complete returns 500 bug

- app/assess/data.py
- app/assess/forms/flag_form.py
- app/assess/routes.py
- app/assess/templates/flag_application.html
- app/assess/templates/macros/assessment_flag.html
- app/assess/templates/macros/flag_history.html
- tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3103
linked PR(https://github.com/communitiesuk/funding-service-design-fund-store/pull/99)
Enable teams selection in flagging
> Enable teams selection in flagging

- app/assess/models/ui/applicants_response.py
- Format currency as GBP to 2 dp
- Also assume all `branched_field`'s are currency
---
> FS-3072, FS-3154: Format as currency

- app/assess/models/ui/applicants_response.py
Revert to fix https://funding-service-design-team-dl.sentry.io/issues/4300323657/?project=4504418515550208&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
---
> FS-3072, FS-3154: Revert format as currency

- app/assess/models/ui/applicants_response.py
https://dluhcdigital.atlassian.net/browse/FS-3154
Adding to change to show monetary values for the correct fields
Go to the Funding required page Funding required, building works and match sub criteria
Questions like How much revenue are you applying for? 1 April 2023 to 31 March 2024 should not show a currency value
> Adding change to dectect currency

- app/assess/data.py
- config/envs/development.py
Fix for debug user
Run the app
> BAU_Fix for local dev with debug user

- app/default/routes.py
- Adds logging to assessment on exceptions, and on `assess_bp`
> BAU: Add logging to assessment exceptions

- app/assess/templates/assessor_tasklist.html
- app/assess/templates/macros/section_element.html
- Make caption's optional, by default it shows
- For "All uploaded documents" it's hidden
---
> BAU: Remove due diligence text

- app/assess/models/fund_summary.py
- Order fund summaries by close date
> BAU: Order fund summaries by close date

- app/default/routes.py
- Don't need error logs for 404s, just info them
> BAU: Change 404 error to info

- .github/workflows/deploy.yml
- .github/workflows/package.yml
- .github/workflows/tag-to-release.yml
- Procfile
- docs/run.md
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
https://dluhcdigital.atlassian.net/browse/FS-3202
Add paketo build and include it in the workflow
- [n/a] Unit tests and other appropriate tests added or updated
Checked container boots and begins producing output
> FS-3202 - Add paketo build and include in workflow

- app/assess/data.py
- app/assess/helpers.py
- app/assess/models/flag_v2.py
- app/assess/models/ui/assessor_task_list.py
- app/assess/routes.py
- app/assess/status.py
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/macros/qa_complete_flag.html
- config/envs/default.py
- tests/api_data/test_data.py
- tests/conftest.py
- tests/test_authorisation.py
- tests/test_helpers.py
- tests/test_routes.py
> refector to new qa_completed endpoint

- app/assess/display_value_mappings.py
- app/assess/models/fund.py
- app/assess/models/ui/assessor_task_list.py
- app/assess/routes.py
- app/assess/templates/macros/scores_justification.html
- app/assess/templates/score.html
- tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3183
The assessment criteria link in now configurable
- Go to score the subcriteria of a scorable section
- Check the url of assessment criteria for night shelter https://mhclg.sharepoint.com/:w:/s/HomelessnessandRoughSleeping/EZn-Dq3eBvFDtdBqhyEZxUUBj_BP53F9TVyI0imX3NdcPw?e=PtmLwH
- Check the url of assessment criteria for Cof https://mhclg.sharepoint.com.mcas.ms/:w:/s/CommunityOwnershipFund/Ecv3iM7U0AtKtyHnzRrQ9dsB0HdMPvHWqAoGn1WrWM7EMA?e=6QpdUT
> Fs 3183 - Configurable assessor link

- app/assess/templates/create_tag.html
> show white for grey tags

- app/assess/templates/assessor_tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-3262
fixed unscored section displayed twice bug
> FS-3262 fix unscored section displayed twice bug

- app/assess/helpers.py
- app/assess/routes.py
- app/assess/tag_routes.py
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/change_tags.html
- app/assess/templates/create_tag.html
- app/assess/templates/macros/fund_dashboard_summary.html
- app/assess/templates/manage_tags.html
- app/create_app.py
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/test_tags.py
BAU - move tag routes into separate file to make maintenance easier and clearer
> moving tag routes to separate blueprint and file

- app/assess/data.py
- app/assess/display_value_mappings.py
- app/assess/models/fund.py
- app/assess/models/round.py
- app/assess/routes.py
- app/assess/templates/assessor_tool_dashboard.html
- app/assess/templates/macros/filter_options.html
- app/assess/templates/macros/tags_table.html
- app/assets.py
- app/static/src/js/helpers.js
- app/templates/head.html
- tests/api_data/test_data.py
- tests/conftest.py
- tests/test_authorisation.py
- tests/test_helpers.py
- tests/test_routes.py
- Metrics will no longer be filtered by the filters, always show all
- "Show tags" now work with client-side JavaScript, no longer need to "Search"
- "All uploaded documents" changes to work per round, instead of per fund
---
- https://github.com/communitiesuk/funding-service-design-fund-store/pull/107
> FS-3249 & BAU: Multiple fixes and changes

- app/assess/helpers.py
Fixing for headers when the first element had no values
Click the download link
> BAU fix for headers

- app/assess/helpers.py
> Revert as fix is in assesment store

- app/assess/data.py
- app/assess/routes.py
- config/envs/default.py
Bug fix: Team dashboard - Progress counter is displaying based on the amount of scored sub criteria for a round.
https://dluhcdigital.atlassian.net/browse/FS-3291
**BEFORE**
**AFTER**
> add fund and round to get progress stats

- app/assess/templates/assessor_dashboard.html
- app/assess/templates/assessor_tasklist.html
- app/assess/templates/change_tags.html
- app/assess/templates/continue_assessment.html
- app/assess/templates/contract_downloads.html
- app/assess/templates/create_tag.html
- app/assess/templates/deactivate_tag.html
- app/assess/templates/edit_tag.html
- app/assess/templates/flag_application.html
- app/assess/templates/macros/banner_summary.html
- app/assess/templates/macros/tag_header.html
- app/assess/templates/manage_tags.html
- app/assess/templates/mark_qa_complete.html
- app/assess/templates/reactivate_tag.html
- app/assess/templates/resolve_flag.html
- app/assess/templates/score.html
- app/assess/templates/sub_criteria.html
This PR fixes margin and spacing issues for the assessment frontend.
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?modal=detail&selectedIssue=FS-3320
> FS-3320-margin-and-spacing-issue-fix

- app/assess/routes.py
- Label action rather than confusing text
> BAU: Change text to action

- app/assess/templates/assessor_tasklist.html
- app/assess/templates/change_tags.html
- app/assess/templates/create_tag.html
- app/assess/templates/deactivate_tag.html
- app/assess/templates/edit_tag.html
- app/assess/templates/macros/fund_dashboard_summary.html
- app/assess/templates/manage_tags.html
- app/assess/templates/reactivate_tag.html
Added some data-qa attributes to make it easier for the e2e Assessment tests to interact with the tagging functionality:
https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/361
N/A
N/A
> BAU: Add data-qa attributes to tagging elements for e2e assessment tests

- app/aws.py
https://dluhcdigital.atlassian.net/browse/FS-3283
Part of PR https://github.com/communitiesuk/funding-service-design-docker-runner/pull/46
-Updated local s3 configuration
- Rebuild the container `docker compose up`
- Create the bucket `docker exec -it <minio_container_id> ./scripts/minio-entrypoint.sh`
- MinIO comes with a UI. Visit http://localhost:9442 to open the MinIO UI. Credentials can be found on `.aws.env` [file](https://github.com/communitiesuk/funding-service-design-docker-runner/blob/e78af38506d19444406494975143c40927742e1a/.aws.env#L2).
> configure for local s3

- app/blueprints/assessments/templates/macros/application_overviews_table_cof.html
- app/blueprints/assessments/templates/macros/application_overviews_table_nstf.html
This PR fixes the margin issue on the assessor dashboard page
> cosmetic-fix/FS-3241-add-filter-dropdowns-for-country-region-and-local-authority

- .github/workflows/deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3414
Change outdated reference to fds to fsd.
- [n/a] Unit tests and other appropriate tests added or updated
- [n/a] README and other documentation has been updated / added (if needed)
> FS-3414 Amend fds to fsd

- app/blueprints/assessments/models/fund_summary.py
- app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
- app/blueprints/services/data_services.py
- Addresses scenarios where application-store may be down
---
> FS-3331: Add fault tolerance on landing page

- app/blueprints/scoring/templates/macros/scores.html
- app/static/src/styles/landing.css
- tests/test_jinja_macros.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-2320
This pull request fixes the accessibility issue for the scores radio buttons by grouping them. 
Macro unit test
> FS-2320-scores-radio-buttons-grouped

- app/blueprints/services/data_services.py
- app/blueprints/tagging/routes.py
https://dluhcdigital.atlassian.net/browse/FS-3254
- Avoid creating duplicate tags.
- Show warning to user & skip API call for duplicate tag creation
> FS-3254 Avoid creating duplicate tags

- app/blueprints/assessments/templates/mark_qa_complete.html
- app/blueprints/assessments/templates/sub_criteria.html
- app/blueprints/flagging/templates/continue_assessment.html
- app/blueprints/flagging/templates/flag_application.html
- app/blueprints/flagging/templates/resolve_flag.html
- app/blueprints/scoring/templates/score.html
- app/blueprints/tagging/templates/create_tag.html
- app/blueprints/tagging/templates/deactivate_tag.html
- app/blueprints/tagging/templates/edit_tag.html
- app/blueprints/tagging/templates/manage_tags.html
- app/blueprints/tagging/templates/reactivate_tag.html
- app/templates/get_help.html
- create_app.py
- tests/test_authorisation.py
- tests/test_routes.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-2318
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-2324
This pull request resolves accessibility issues related to the following items:
- Unique page title
- Error page title
- Margin fix
- added GOV.UK suffix to the service title 
unit test
> FS-2324-2318-error-handling-and-unique-page-title

- app/blueprints/scoring/templates/macros/scores_justification.html
This PR is just to fix the margin in rescore page
> FS-3450-margin-fix-rescore-page

- .github/workflows/tag-to-release.yml
* Package is no longer a valid workflow file so also needs removing from the tag to release workflow
+ref: FS-3311
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3311: Removing defunct workflow file

- app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
https://dluhcdigital.atlassian.net/browse/FS-3475
Description
Make the feedback link available when round is live
> FS-3475 fix display of export links

- copilot/fsd-assessment/manifest.yml
* Add Sentry Environment Variable
* Remove specific RSA key secret
+ref: BAU
+semver: minor
- [ X ] Unit tests and other appropriate tests added or updated
- [ X ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> BAU Reverting values, adding sentry

- requirements.txt
> BAU: bump utils

- app/blueprints/assessments/routes.py
- app/blueprints/assessments/templates/assessor_dashboard.html
- app/blueprints/assessments/templates/macros/application_overviews_table_cof.html
- app/blueprints/assessments/templates/macros/application_overviews_table_cyp.html
- app/blueprints/assessments/templates/macros/application_overviews_table_nstf.html
- app/blueprints/assessments/templates/macros/application_status_column.html
- app/blueprints/assessments/templates/macros/filter_options.html
- app/blueprints/flagging/forms/flag_form.py
- app/blueprints/flagging/templates/flag_application.html
- app/blueprints/shared/filters.py
- config/display_value_mappings.py
- config/envs/development.py
- create_app.py
- tests/api_data/test_data.py
- tests/conftest.py
- tests/test_authorisation.py
- tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3588
Added assessment dashboard for CYP fund
> FS-3588 added dashboard for cyp

- app/blueprints/assessments/helpers.py
- app/blueprints/assessments/routes.py
- app/blueprints/tagging/routes.py
- tests/test_tags.py
Patch on tags
https://dluhcdigital.atlassian.net/browse/FS-3350
https://dluhcdigital.atlassian.net/browse/FS-3652
> only show active tags in assessment dashboard and the change tags screen

- app/blueprints/assessments/models/fund_summary.py
- app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
- app/blueprints/services/models/round.py
Fix export-feedback-link display for CYP
> Fix-export-feedback-link-cyp

- app/blueprints/services/models/flag.py
https://dluhcdigital.atlassian.net/browse/FS-3548
- Fix the bug associated with flag updates order
- Make the flag updates order as ascending based on date created
> FS-3548 sort the updates based on time created

- app/blueprints/assessments/models/applicants_response.py
- app/blueprints/services/data_services.py
https://dluhcdigital.atlassian.net/browse/FS-3660
https://dluhcdigital.atlassian.net/browse/FS-3674
- Fix broken PDF download link
- do not return 404 if  `all_uploads_documents` is empty
- fix `monthYearField` display estimation for multi-input field
> FS-3660 do not return 404 if  `all_uploads_documents` is empty

- app/blueprints/assessments/models/applicants_response.py
https://dluhcdigital.atlassian.net/browse/FS-3708
> FS-3708 fix the execption on organisation page

- app/templates/macros/theme/question_above_answer_html.jinja2
https://dluhcdigital.atlassian.net/browse/FS-3702
Fixing missing underline when Question is above answer 
> FS-3702 Adding underline

- app/templates/macros/theme/question_above_href_answer_list.jinja2
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-3464
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-3466
Cosmetic fix for the file upload component
> FS-3464-3466-cosmetic-fix-for-file-upload-component

- .github/workflows/combine-prs.yml
Workflow to combine dependabot PR's
> add combine PR workflow

- .github/workflows/copilot_deploy.yml
- .github/workflows/environment.yml
https://dluhcdigital.atlassian.net/browse/FS-3718
Add deploy to dev workflow and the other environments as a parameterised block.
- [n/a] Unit tests and other appropriate tests added or updated
- [n/a] README and other documentation has been updated / added (if needed)
> FS-3718 - Add dev deploy

- .github/workflows/copilot_deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
> BAU - pass environment

- app/blueprints/assessments/routes.py
- app/blueprints/authentication/validation.py
- app/blueprints/tagging/routes.py
- app/blueprints/tagging/templates/create_tag.html
- tests/conftest.py
- tests/test_tags.py
- tests/test_validation.py
https://dluhcdigital.atlassian.net/browse/FS-3290
https://dluhcdigital.atlassian.net/browse/FS-3762
Fix the manage tag error behaviour and patch a tag regression bug.
> Fs 3290 fix create tag errors

- app/blueprints/tagging/routes.py
- app/blueprints/tagging/templates/create_tag.html
- tests/test_tags.py
Patch create tag - retain error value
> retain bad value to display back to user

- config/display_value_mappings.py
https://dluhcdigital.atlassian.net/browse/FS-3753
Fix bug associated with search by ref or project name
> FS-3753 modify search_in for DPIF

- app/blueprints/assessments/templates/sub_criteria.html
- app/blueprints/services/models/fund.py
- app/blueprints/shared/templates/macros/sub_criteria_heading.html
https://dluhcdigital.atlassian.net/browse/FS-3757
https://dluhcdigital.atlassian.net/browse/FS-3751
> fix sub criteria heading on score template

- app/blueprints/tagging/routes.py
https://dluhcdigital.atlassian.net/browse/FS-3781
* make tags unique to a round
> make tags unique to round

- copilot/fsd-assessment/manifest.yml
* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3780 Updating manifest

- .github/workflows/copilot_deploy.yml
- copilot/fsd-assessment/manifest.yml
Increase CPU and RAM requirements
> BAU increase cpu

- .github/workflows/copilot_deploy.yml
* Update workflow for deployment to uat and production to only occur after post-deploy tests pass
+ref: FS-3797
+semver: minor
> FS-3797 - Update copilot workflow

- app/blueprints/assessments/templates/activity_trail.html
- app/blueprints/assessments/templates/assessor_tasklist.html
- app/static/src/styles/landing.css
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3685
- display project name on the banner correctly
- View activity trial button margin fix
> bug fixes:

- copilot/fsd-assessment/manifest.yml
* Adding a variable to ease testing capability on the dev and test environments
+ref: BAU
+semver: minor
> BAU - Add environment vars for dev and testing

- app/blueprints/assessments/templates/activity_trail.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3836
> FS-3836-hide-amount-requested-for-dpif-fund-and-workflow-status-fix

- app/templates/macros/theme/question_above_answer_html.jinja2
https://dluhcdigital.atlassian.net/browse/FS-3783
fix accessibility violation bug
> fix accessibility violation bug

- .github/workflows/copilot_deploy.yml
- copilot/fsd-assessment/manifest.yml
Amend production to prod for pre-award URLs
> FS-3797 - Amend production to prod for deployment

- create_app.py
https://dluhcdigital.atlassian.net/browse/FS-3804
Fix bug in preventing display of maintenance page on PAAS environemnt
> Fix display maintenance page

- app/templates/base.html
- app/templates/head.html
https://dluhcdigital.atlassian.net/browse/FS-3606
Added google generated GA4 tag code to assessment frontend with consent default to denied - set base to include no script GTAG code 
> Added GA4 tag code to assessment frontend with consent default to denied

- copilot/fsd-assessment/addons/fsd-assessment.yml
Add fsd-form-uploads-* bucket access to assessment.
> BAU - add s3 form uploads permission to assessment

- app/blueprints/assessments/activity_trail.py
- app/blueprints/assessments/routes.py
- app/blueprints/scoring/templates/macros/scores_justification.html
- tests/test_activity_trail.py
https://dluhcdigital.atlassian.net/browse/FS-3837
fixed DPIF sub-criteria letter case
> FS-3837 fix dpif letter case

- copilot/fsd-assessment/manifest.yml
Split hsoted zones for different domains
> corrected hsoted zones

- copilot/fsd-assessment/manifest.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
> reverting split of hosted zones

- app/blueprints/assessments/templates/macros/filter_options.html
- app/static/src/styles/landing.css
- config/envs/default.py
- copilot/fsd-assessment/addons/fsd-assessment.yml
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3252
> FS-3252-fix-margin-for-search-button-on-team-dashboard

- app/static/src/styles/landing.css
search button margin set to -100px on team dashboard after discussing with @rayhan15243
> FS-3252-adjust-margin-for-search-button-team-dashboard

- app/blueprints/assessments/models/fund_summary.py
- app/blueprints/services/models/round.py
- tests/api_data/test_data.py
- Show assessment as open if past the assessment start date
> FS-3785: Assessment start date

- app/blueprints/assessments/routes.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3992
small bug fix: assessment status fix for page export application data.
> FS-3992-assessment-status-fix-for-export-application-data-page

- app/blueprints/assessments/templates/activity_trail.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3833
when no activities results found on activity trail page, the page displays a message "No matching results" which is the same as dashboard empty state message
> FS-3833-displays-message-when-no-matching-results-found

- app/blueprints/assessments/templates/assessor_tool_dashboard.html
https://dluhcdigital.atlassian.net/browse/FS-3769
- fix `show all sections` dropdown when fund length=0
> FS-3769 show funds in dashboard only when length>0

- requirements-dev.in
- requirements-dev.txt
https://dluhcdigital.atlassian.net/browse/FS-2713
- updated requirements
> FS-2713 single config file for all code formatters

- app/blueprints/tagging/templates/edit_tag.html
- app/static/src/styles/govuk-overrides.css
https://dluhcdigital.atlassian.net/browse/FS-3292
https://dluhcdigital.atlassian.net/browse/FS-3298
- fix deactivate tag accessibility issue
- fix deactivate tag font issue
> FS-3292 FS-3298 fix deactivate tag accessibility issue

- app/blueprints/assessments/models/fund_summary.py
- app/blueprints/services/data_services.py
- config/envs/default.py
- tests/api_data/test_data.py
- tests/conftest.py
- Refactor assessment front-end to use new `get-stats` bulk endpoint
- https://github.com/communitiesuk/funding-service-design-assessment-store/pull/417
---
> BAU: Refactor to use `get-stats` bulk endpoint

- app/blueprints/assessments/templates/assessor_dashboard.html
- app/blueprints/assessments/templates/macros/application_overviews_table_cof_eoi.html
- app/blueprints/assessments/templates/macros/filter_options_eoi.html
- config/envs/development.py
https://dluhcdigital.atlassian.net/browse/FS-4102
Adding configuration for COF EOI
> FS-4102 - Configuration for COF EOI

- app/blueprints/assessments/models/fund_summary.py
- app/blueprints/assessments/templates/assessor_tasklist.html
- app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
- app/templates/macros/banner_summary.html
- tests/test_jinja_macros.py
- tests/test_routes.py
FS-4159
- Updated tasklist content to match prototype
FS-4155 U
- Updated links on assessment tool dashboard
> Fs 4159 tasklist content

- app/blueprints/assessments/activity_trail.py
- app/blueprints/assessments/routes.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4212
The score checkbox filter is removed for fund round COF-EOI from actvity trail
> FS-4212-hide-score-checkbox-filter-for-cofeoi-from-activit-trail

- app/blueprints/assessments/routes.py
- app/blueprints/assessments/templates/assessor_tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-4217
https://dluhcdigital.atlassian.net/browse/FS-4226
- Disabled Flag history for EOI
- Fixed sorting columns for EOI dashboard
- Fixed alignment of buttons on application page
> FS-4226-4217-EOI-changes

- app/blueprints/assessments/models/applicants_response.py
- app/blueprints/shared/filters.py
https://dluhcdigital.atlassian.net/browse/FS-4216
Fixed the answer display formatting on sub-criteria page
> FS-4216 update the formating for subcriteria

- app/blueprints/assessments/helpers.py
- app/blueprints/assessments/routes.py
- app/blueprints/assessments/templates/activity_trail.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4200
fix cosmetic issues for export applicant information for cof-eoi
> FS-4200-fix-cosmetic-issues-for-export-applicat-information-data

- app/blueprints/assessments/models/applicants_response.py
- tests/test_applicators_response.py
https://dluhcdigital.atlassian.net/browse/FS-4269
- Revert changes form previous [PR](https://github.com/communitiesuk/funding-service-design-assessment/pull/586)
- Fixed bug - file upload not showing for `Upload asset valuation or lease agreement` question
> FS-4269 revert file changes

- requirements-dev.txt
- requirements.txt
PR is being reverted for further investigation since it seems to be impacting the UI of assessment 
ticket for reference 
https://dluhcdigital.atlassian.net/browse/FS-4317
> revert-dependabot-govuk-frontend-jinja-from-2.5.0-to-3.0.0

- app/blueprints/assessments/helpers.py
- app/blueprints/assessments/routes.py
- app/blueprints/shared/filters.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4328
The timestamp converted to bst for Export applicant information download file.
> FS-4328-convert-timestamp-to-bst-for-export-applicant-information

- app/blueprints/assessments/helpers.py
- app/blueprints/assessments/models/full_application.py
- tests/test_full_application.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4335
Converted utc timestamp to bst
> FS-4335-convert-utc-to-bst-for-pdf-download-file

- app/blueprints/assessments/routes.py
- https://dluhcdigital.atlassian.net/browse/FS-4008
- Code refactor to fix assessment status not being displayed
> FS-4008: Add Full Application Comments

- app/blueprints/assessments/templates/assessor_tasklist.html
- app/blueprints/assessments/templates/macros/comments.html
- app/blueprints/assessments/templates/macros/comments_box.html
- https://dluhcdigital.atlassian.net/browse/FS-4008
- Cancel button added for commentator
- Styling refactor
> FS-4008: Cancel button added for commentor

- app/blueprints/assessments/templates/assessor_tasklist.html
https://dluhcdigital.atlassian.net/browse/FS-4008
- Allowing commenter to view their or other commenters' comments on entire application page
- Allowing commenters to add comments on entire application page
> FS-4008: Allowing commenter to view or add comments on entire application page

- app/blueprints/themes/deprecated_theme_mapper.py
- config/themes_mapping.py
https://dluhcdigital.atlassian.net/browse/FS-4388
Adding COF R4W2 config 
> FS-4388 Adding COF R4W2 assessment config

- app/blueprints/assessments/routes.py
- app/blueprints/assessments/templates/assessor_dashboard.html
- app/blueprints/assessments/templates/macros/application_overviews_table_hsra.html
- app/blueprints/assessments/templates/macros/filter_options_hsra.html
- app/blueprints/scoring/forms/scores_and_justifications.py
- app/blueprints/scoring/helpers.py
- app/blueprints/services/models/fund.py
- config/display_value_mappings.py
- config/envs/development.py
- config/themes_mapping.py
- tests/conftest.py
- tests/test_authorisation.py
- tests/test_jinja_macros.py
https://dluhcdigital.atlassian.net/browse/FS-4389
- joint_application_options added as a mapping of boolean to yes/no
- Filter and headers created and added for HSRA according to requirements given
- Going through HSRA in Assessment
> FS-4389: HSRA Assessment Config

- .github/workflows/copilot_deploy.yml
Updating run name to remove dev from auto deploys
> Update run name

- create_app.py
https://dluhcdigital.atlassian.net/browse/FS-3873
- cookie_policy added to unprotected_routes to make it available at login page
> FS-3873: cookie_policy added to unprotected_routes to make it available

- README.md
- app/blueprints/assessments/routes.py
- app/blueprints/assessments/templates/fund_dashboard.html
- app/blueprints/shared/routes.py
- tests/deprecated/dashboard_per_fund.py
- tests/route_testing_conf.py
- tests/test_maintenance.py
- tests/test_routes.py
Renaming assessor dashboard to be fund dashboard (more accurate reflection of the purpose). Updated references and paths as well.
N/A
> Change assessor dashboard to fund dashboard

- app/blueprints/assessments/helpers.py
- app/blueprints/assessments/routes.py
- app/blueprints/assessments/templates/fund_dashboard.html
- app/blueprints/assessments/templates/macros/application_overviews_table_all.html
- app/blueprints/services/data_services.py
- app/static/src/styles/govuk-overrides.css
- config/envs/default.py
- tests/api_data/test_data.py
- tests/conftest.py
- tests/test_data_operations.py
- tests/test_helpers.py
- tests/test_maintenance.py
- tests/test_routes.py
This PR introduces the 'assigned to you' tab for users to view applications that have been assigned to them.
Currently an application will have to be manually assigned to a user (as the relevant UI pages have not been implemented). Once done, the user should be able to see the application on the 'assigned to you' tab.
> Assigned to you tab for work allocation

- copilot/fsd-assessment/manifest.yml
remove additional alias as this is not being used
> BAU: remove additional alias

- app/blueprints/assessments/routes.py
Fix for search that was broken due to a mismatch between the drop down selection option 'All'.
> Mismatch between 'All' option in assigned to drop-down selection

- app/blueprints/assessments/helpers.py
- app/blueprints/assessments/routes.py
- tests/test_helpers.py
The assigned_to column in the dashboard requires a more complex sort based on the assignees. This PR implements the sort function required. 
> Implemented sorting function for assigned to column

- app/blueprints/assessments/templates/macros/application_overviews_table_all.html
- app/blueprints/assessments/templates/select_assessor.html
Add missing aria labels for checkboxes in assignment flow.
> Add aria labels for checkboxes

- app/blueprints/assessments/templates/macros/application_overviews_table_all.html
- tests/api_data/test_data.py
- tests/test_routes.py
For the Fund dashboard: comment out action columns (not in use) and add date submitted column
> BAU: Amend fund dashboard columns

- copilot/fsd-assessment/manifest.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
> FLS-795: Basic auth added
