communitiesuk/funding-service-design-assessment

manifest.yml
Assessment was borken on test after last merge as the test manifest didn't contain the URLs for fund_store or assessment_store. This adds them
=> added api URLs to test manifest

manifest.yml
Add assessment routes (this is important to be able to test authentication and other functionality which depends on a shared domain)
=> FS-2045: Add assessment domain routes

app/auth.py, app/create_app.py, config/envs/development.py
- Refactor global auth functionality from create_app to new auth_protect() function
- Add DEBUG_USER_ROLE env var to development config (defaulting to "LEAD_ASSESSOR") 
- Add DEBUG_USER config var (in development config only) which creates a dict of user attributes with roles defined by DEBUG_USER_ROLE env var, to enable local development debugging of user roles
=> BAU: Add functionality to switch auth user roles in development via config var

app/assess/data.py, config/envs/default.py, config/envs/development.py, config/envs/unit_test.py, manifest.yml
Found in the course of another story. This S3 PaaS config was previously in `data.py` which made it difficult to reason about how S3 was configured. This moves it to the shared config.
=> BAU: move S3 config into main config file

app/assess/templates/assessor_dashboard.html
Inline style removed to fix console errors, Link is already right aligned
=> Removing inline style

app/assess/routes.py, app/assess/templates/assessor_tasklist.html, app/assess/templates/macros/assessment_flag.html
Quick fix for the following type things:
- Extra `</div>` causing styling errors on UAT
- Typo causing "Flag application" button to show on UAT when there is already a flag
- Fix styling of role badge on flag banner (LEAD_ASSESSOR -> Lead assessor)
https://assessment.uat.gids.dev/assess/application/b823cf41-e8b7-4556-8265-692b3ee992f9
Screenshots of before: (broken styling & wrong "flag application" button)
Screenshots of after: (fixed styling & no "flag application" button)
=> BAU: Fix typo in route, remove unnecessary closing div

app/auth.py, app/create_app.py, tests/test_routes.py
- Update unprotected_routes list to include /healthcheck route and remove empty route.
- Add tests to ensure homepage routes and /healthcheck route are accessible
=> FIX: Allow /healthcheck route past auth

app/assess/forms/flag_form.py, app/assess/routes.py, app/assess/templates/assessor_tasklist.html, app/assess/templates/flag_application.html, app/assess/templates/macros/comments.html, app/assess/templates/macros/comments_box.html, app/assess/templates/macros/comments_summary.html, app/assess/templates/sub_criteria.html, tests/test_jinja_macros.py
Pull request includes changes for multiple things:
- Anchors for comments
- I've refactored and taken the duplicate comment creation logic and put it at the top
- We handle scenarios for initially expanding a comment, and submitting it
- Having this at the top means we can return redirects when required, otherwise continue the flow without indentation
- Role checks for displaying Flags and "Flag application" button 
- Now, only Assessor's and Lead Assessors can create & view flags
- Also refactored the form to use govukTextarea rather than out own logic
Edit:  Have since pushed https://github.com/communitiesuk/funding-service-design-assessment/pull/107/commits/dc89424e10bc082bbaf52ceecd2c08bbe9f439ef to include some styling/qol changes, i.e. using proper error messages instead of …
=> FS-2125, FS-2126, BAU: Anchors for comments, Flag application validation

app/assess/templates/macros/comments_summary.html
Updated contents as per the prototype for scoring page for comments summary section
=> FS-2129-update-comments-summary-section-with-theme-names-and-no-comment-message

app/assess/templates/macros/criteria_element.html
- Set sub criteria width to one half, should enable consistency even with long names
**Before:**
**After:**
=> FS-2136: Set sub criteria width to one half

app/assess/routes.py
- Only call the progress endpoint if we actually have data, if we don't, no point in calling it
Fixes: 
- https://communities-govuk.slack.com/archives/C02PHBER287/p1673449332218439
- https://sentry.io/organizations/funding-service-design-team-dl/issues/3850987122/?referrer=slack
=> BAU: Only call progress endpoint if we have data

app/assess/templates/macros/comments.html, app/assess/templates/macros/comments_box.html
-  Update comment box styling to reflect prototype
Covers:
- https://digital.dclg.gov.uk/jira/browse/FS-2154
- https://digital.dclg.gov.uk/jira/browse/FS-2153
Before:
After:
=> FS-2153: Update comment box styling to reflect prototype

app/assess/templates/macros/scores_justification.html, app/static/src/styles/govuk-overrides.css
- Formatted the highest_role using `all_caps_as_human`
- Add margins to match prototype spacing
- Change button names to match prototype
- Add classes to change button styling to prototype
- Add styling for latest score box
Video demo:
https://user-images.githubusercontent.com/117724519/211872026-01234017-f598-40cb-b84f-0974d27f4164.mp4
=> FS-2155, FS-2157: Fix score styling to match proto

manifest.yml
Add missing config to manifests, should fix Sentry errors e.g.
=> BAU: add account store to dev/test manifests

app/assess/templates/flag_application.html
Text area for section to flag now macthes prototype
=> FS-2160: Text area now matches prototype

app/assess/data.py, app/assess/routes.py, app/assess/templates/assessor_tasklist.html, app/assess/templates/macros/assessment_flag.html, app/assess/templates/macros/banner_summary.html, tests/test_jinja_macros.py
Banner for STOPPED Assessment Completed
- Assessment Stopped Header displayed in place of "Flagged" when an application has a "STOPPED" flag
- The banner summary also now has "Stopped" in place of the workflow_status if the flag is present
- Tests have been written to check if the UI is showing accurate to Flagged/Assessment Stopped heading
- Banner_summary now has a default parameter of flag=None, and the banner only adjust to the stopped flag is this flag is not None
=> Fs 2008 stopped banner

app/assess/routes.py, app/assess/templates/macros/justification.html, app/assess/templates/macros/scores_justification.html, tests/test_jinja_macros.py
The "justification" macro is designed to save any rationale provided by the user, even if the assessment has not been scored yet. This means that if the user enters text into the text area for the rationale, but does not provide a score for the assessment, the page will still save the rationale text entered by the user.
=> FS-2177-save-score-rationale-without-scores

app/assess/helpers.py, app/assess/routes.py, app/assess/templates/assessor_tasklist.html
Always call determine display status so that templates have a value to render for display_status.
Allow flagging workflow on completed applications.
=> Fix determine display status

app/assess/helpers.py, app/assess/routes.py, app/assess/templates/resolve_flag.html
Saves the radio field option data when clicked  and preselect the radio filed option when page is reloaded
=> FS-2228-save-radio-button-selection-on-flag-resolve-without-filling-reason

app/assess/templates/components/application_overviews_table.html, app/assess/templates/question.html
A condition has been re-implemented, which states that the progress percentage of an assessment will only be visible when the status is "In progress" and will not be displayed when the status is "Assessment complete." This means that once the assessment is completed, the percentage of completion will no longer be shown.
=> FS-2247-progress-percentage-removed-if-status-assessment-complete

app/assess/routes.py, app/assess/templates/assessor_dashboard.html, app/assess/templates/assessor_tasklist.html, app/assess/templates/flag_application.html, app/assess/templates/resolve_flag.html, app/assess/templates/sub_criteria.html, app/templates/base.html, requirements-dev.in, requirements-dev.txt, tests/api_data/endpoint_data.json, tests/test_routes.py
Similar approach to https://github.com/communitiesuk/funding-service-design-frontend/pull/243 and https://github.com/communitiesuk/funding-service-design-authenticator/pull/113 to set unique `<title>` tags for pages.
* Pass through theme name to subcriteria template so it is available for title
* Some hacky code is needed to workaround `score` being set by a `theme_id`
=> FS-2287: Set unique title tags for pages

app/assess/templates/assessor_dashboard.html, app/assess/templates/assessor_tasklist.html, app/assess/templates/components/application_overviews_table.html
Functionality added to hide the status of application assessment for commenters because  the commenters should not have the visibility to see the status column in the assessment dashboard and on the assessment overview banner. 
Assessor Dashboard:
Assessment overview:
=> FS-2268-hide-dashboard-status-for-commenters

app/assess/templates/assessor_tasklist.html, app/assess/templates/continue_assessment.html, app/assess/templates/flag_application.html, app/assess/templates/macros/banner_summary.html, app/assess/templates/mark_qa_complete.html, app/assess/templates/resolve_flag.html, app/assess/templates/sub_criteria.html
Hide banner status from  "COMMENTER"
Dashboard:
Tasklist overview:
Scored Page:
Unscored page:
=> FS-2268-bug-fix-hide-status-from-commenter

app/assess/routes.py, app/assess/templates/macros/sub_criteria_navbar.html, app/assess/templates/score.html, app/assess/templates/sub_criteria.html, tests/test_routes.py
Previously we rendered the scoring pages by overloading the `theme_id` parameter with `score`. This caused a lot of hacky workarounds and branching in templates to ensure the correct things were rendered and meant `theme_id` couldn't be safely used semantically i.e. to lookup a `Theme` class.
This moves all scoring to its own route `/application_id/<application_id>/sub_criteria_id/<sub_criteria_id>/score`
This is purely a refactor, there should be no change in any page functionality.
=> FS-2294: refactor score page to own route

app/assess/templates/macros/sub_criteria_navbar.html
Fix TODOs added in previous story: https://github.com/communitiesuk/funding-service-design-assessment/pull/176
As-per the [prototype](https://fsd-pre-award.herokuapp.com/s26-assessment/scoring/scoring), the currently selected item in the navbar should not be a link. Also the 'Score this subcriteria' item was not appearing at all when on that page, which is also fixed by this PR.
=> BAU: only make nav item link if not current page

app/assess/data.py, app/assess/routes.py, config/envs/default.py, tests/api_data/endpoint_data.json, tests/test_routes.py
Now that https://github.com/communitiesuk/funding-service-design-assessment-store/pull/123 has been merged and deployed we no longer need to pass `theme_id=score` to the comments endpoint.
This also refactors how the URL is built so we can strip the parameter from the generated query string if `None`.
=> FS-2272: don't pass theme_id=score to comment endpoint on score page

.github/workflows/govcloud.yml
Disabling e2e tests on Dev as it's giving false positives on some test runs. This is mainly due to the environment being constantly deployed per commit which disrupts the e2e test run.
Evidence that e2e application and assessment passes when running against Test env with the e2e tests not running against Dev:
https://github.com/communitiesuk/funding-service-design-frontend/actions/runs/4222595381
N/A
N/A
=> BAU - Disable e2e tests running against Dev env

.github/workflows/s3-zip.yaml
Change description
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
[ - ] Unit tests and other appropriate tests added or updated
[ - ] README and other documentation has been updated / added (if needed)
[ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)
=> tagging action permissions update

app/assess/data.py
When making the request for bulk-accounts, we unnecessarily send the same ids lots of times, by putting it into a set then back to a list, we can ensure each id is only sent once.
```python
list(set(['a', 'a', 'b'])) # ['b', 'a']
```
N/A - This is a quick tiny fix to delay the issue from re-occurring on from e2e tests, but in theory it could still happen if lots of unique users were to comment on the same application, so I think it would be good to change it from using query parameters based on that, although that's a lot less likely to occur after we de-duplicate the ids.   More info on the [JIRA](https://digital.dclg.gov.uk/jira/browse/FS-2371).
=> FS-2371: Fix for duplicate ids in bulk-accounts endpoint

app/assess/templates/score.html, app/assess/templates/sub_criteria.html
FS-2303 Display error summary banner
Added the banner to display the error summary when score inputs aren't filled. Banner has also been added for when comment box is not filled.
=> Fs 2303 error summary scores comments

.github/workflows/govcloud.yml
Copied concurrency keys from these PRs as this repo does not use the shared workflow from the Workflows repo:
https://github.com/communitiesuk/funding-service-design-workflows/pull/43
https://github.com/communitiesuk/funding-service-design-workflows/pull/45
N/A
N/A
=> FS 2385: Copy concurrency keys from Workflow repo Assessment

app/assess/data.py, tests/api_data/test_data.py, tests/test_export.py
Sentry raised [this](https://funding-service-design-team-dl.sentry.io/issues/4027062124/?referrer=slack) error as the export file functionality was tripping over generating the file names for an application. This was caused by a key error being raised if a file field had no answer (i.e. user had not submitted a file for an optional file-upload field). We have now added a check to only generate the list of file names for file-upload fields with an answer in this PR.
- [ ✅ ] Unit tests and other appropriate tests added or updated
- [ 🔕 ] README and other documentation has been updated / added (if needed)
- [ ✅ ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
New test to catch this in the …
=> BAU-export-file-empty-answer-key-bug-fix

app/assess/templates/assessor_tasklist.html, app/assess/templates/components/application_overviews_table.html, app/assess/templates/macros/criteria_element.html, app/assess/templates/macros/section_element.html, app/assess/templates/sub_criteria.html
https://digital.dclg.gov.uk/jira/browse/FS-2388
There were two accessibility violations against the Assessor dashboard and Assessment overview page where the same ids were not unique in those pages. These ids were used for the e2e test selectors. I have now replaced them with the data-qa attribute and they now meet WCAG 2.1 A standards. 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
A separate PR has been raised in the e2e repo to update the selectors from IDs to data-qa. 
Run axe dev tools against the Assessor dashboard and Assessment overview page. 
N/A
=> Fs 2388 - Replace ids with data-qa (for e2e tests) 

app/assess/templates/continue_assessment.html, app/assess/templates/flag_application.html, app/assess/templates/mark_qa_complete.html, app/assess/templates/resolve_flag.html, app/assess/templates/score.html
https://digital.dclg.gov.uk/jira/browse/FS-2388
I forgot to add the data-qa attributes to the assessment overview back link for the other pages which were causing the e2e tests for Assessment to fail.
N/A
N/A
=> FS 2388 - Add remaining data-qa attributes to the back link

app/assess/routes.py, app/assess/templates/macros/banner_summary.html, app/assess/templates/sub_criteria.html
FS-2347 Resolve QA Complete status for sub criteria sections
Fixed the bug - The status in the sub criteria pages is showing "Assessment complete" when the actual status is "QA Complete".
Unit tests are checked & passed..
1. Login to Assessment
2. Complete assessment for an application 
3. Mark the assessment as QA complete
4. Flag the application 
5. Resolve the flag as Query resolved
6. Click on any of the sub criteria pages and observe
=> fix the display status in sub criteria

app/assess/forms/continue_application_form.py, app/assess/forms/resolve_flag_form.py, app/assess/templates/continue_assessment.html, app/assess/templates/flag_application.html, app/assess/templates/resolve_flag.html
The issue on JIRA
https://digital.dclg.gov.uk/jira/browse/FS-2376
- Fixed missing error boxes for certain pages
- Unit tests are checked & passed
- Visit the below pages & click submit without selecting any option or adding data in the fields.
- Error box should appear on the top of the page
=> added error box for missing pages

app/assess/routes.py, app/assess/templates/continue_assessment.html, app/assess/templates/flag_application.html
Jira Issue Link
https://digital.dclg.gov.uk/jira/browse/FS-2373
Made to redirect to assessment application overview page when clicked on cancel button
look at the description in jira ticket
=> redirect to assess_bp page when cancel is clicked

app/assess/templates/assessor_dashboard.html, app/assess/templates/assessor_tasklist.html, app/assess/templates/components/application_overviews_table.html, app/assess/templates/macros/assessment_flag.html, app/assess/templates/macros/qa_complete_flag.html, app/assess/templates/macros/scores.html, app/assess/templates/macros/scores_justification.html, app/assess/templates/score.html, app/templates/base.html
https://digital.dclg.gov.uk/jira/browse/FS-2322
The DAC Accessibility Report (attached) reported that status messages could not be programmatically determined through role or properties in order that they could be presented to users by assistive technologies without receiving focus.
When no results are returned, place the results information inside a separate div and use the role of ‘status’ on the <div> which will inform screen reader users of the change in status on the page. Using role=status to present status messages.
When scoring validation fails, use an error summary on the page which contains a h2 heading ‘There is a problem’ and uses the role of alert to inform screen reader users that there are errors on the page with skip links to …
=> add accessibility tags to elements

app/assess/templates/macros/fund_dashboard_summary.html
https://digital.dclg.gov.uk/jira/browse/FS-2577
https://digital.dclg.gov.uk/jira/browse/FS-2567
Added data attribute to enable the e2e tests for Assessment to click on the view assessments link in the Assessor Dashboard Tool.
Run e2e tests locally by running `npx wdio run ./wdio.conf.js --suite assessment_lead_assessor` for Lead Assessor e2e journey or
`npx wdio run ./wdio.conf.js --suite assessment_assessor` for Assessor e2e journey 
N/A
=> FS-2577 - Add data attribute to view assessments link in Assessor Dashboard Tool

app/assess/routes.py, app/assess/templates/macros/banner_summary.html, app/assess/templates/mark_qa_complete.html, app/assess/templates/score.html
This super tiny PR resolves a small bug related to the banner status of the subcriteria scoring page.
- FS-2548: The incorrect display of status when the application was flagged as QA COMPLETED, where "Assessment complete" was shown instead of "QA complete".
- FS-2572: The QA complete status was not displayed in the correct format.
=> FS-2548-2572-bug-fix-subcriteria-scoring-status

app/assess/templates/macros/sub_criteria_navbar.html
https://digital.dclg.gov.uk/jira/browse/FS-2651
Added data qa attribute to the sub criteria theme link to ensure that the e2e test for commenters in assessment can interact with the link easily. 
Once this PR is merged run `npx wdio run ./wdio.conf.js --suite assessment_commenter` locally and the test should pass. 
N/A
=> FS-2651: Add data qa attribute to sub criteria theme link

manifest.yml
Increasing the healthchecks timeout to 20 seconds as the app on Test env has been restarting recently at random times during some e2e test runs which disrupts the tests.  
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#health-check-invocation-timeout
https://cli.cloudfoundry.org/en-US/v6/v3-set-health-check.html
Once this PR is merged run the e2e tests for Assessment locally and the tests should pass without any environment issues. 
N/A
=> BAU: Increase health-check-invocation-timeout to 20 seconds

.vscode/launch.json, Dockerfile, app/assess/data.py, app/assess/routes.py, config/envs/default.py, tests/conftest.py, tests/test_routes.py
Jira Ticket
https://digital.dclg.gov.uk/jira/browse/FS-2618
Implement count based on filter returns. Updated Dockerfile to comply with debugger(https://github.com/communitiesuk/funding-service-design-docker-runner/pull/33)
- Open the Assessment dashboard & select a fund/round
- Apply any filters & observe the count
=> Fs 2618 count for filters

manifest.yml
Adding a little more memory, we're seeing seemingly random `502`s and it may be the memory causing the hiccups.
We're using around 95% idle so... maybe it's that?
```
name:              funding-service-design-assessment-test
requested state:   started
routes:            funding-service-design-assessment-test.london.cloudapps.digital, assessment.test.fundingservice.co.uk, assessment.test.gids.dev
last uploaded:     Mon 15 May 15:37:32 BST 2023
stack:             cflinuxfs3
buildpacks:
name                                                   version   detect output   buildpack name
https://github.com/cloudfoundry/python-buildpack.git   1.8.9     python          python
type:           web
sidecars:
instances:      1/1
memory usage:   64M
state     since                  cpu    memory …
```
=> BAU: Update memory on assessment test

manifest.yml
Related to https://github.com/communitiesuk/funding-service-design-assessment/pull/247
https://digital.dclg.gov.uk/jira/browse/FS-2683
There are still a very small amount of 502s being returned since increasing to 128mb. So I'm increasing the memory further on assessment test. Frontend test has 256mb of memory as well.
Run e2e tests for Assessment locally or via the manual workflow in the e2e checks repo after this PR has been merged and the tests should run smoothly without any env issues. 
Also run `cf app funding-service-design-assessment-test` to check memory after this memory bump has been merged to Test env. 
N/A
=> FS-2683 - Increase memory to 256mb on Assessment frontend test

app/assess/templates/assessor_tasklist.html
Very small PR fixes the bug when the application is flagged, the qa complete button should not be displayed.
=> FS-2773-bug-fix-qa-complete-button-overrides-the-flagged

.vscode/launch.json, app/assess/models/fund_summary.py, config/envs/default.py, config/envs/development.py
https://digital.dclg.gov.uk/jira/browse/FS-2993
Currently, only closed rounds are shown in the Assessment dashboard
During development, we want to see all open, closed, active & inactive rounds in the assessment dashboard.
Added a variable `SHOW_ALL_ROUNDS` & set this to `true` in development config. If `True` all rounds are displayed in the Assessment dashboard.
Also changed the port number in launch json to sync with docker-runner
=> add showallrounds env for developer productivity

app/assess/templates/continue_assessment.html, app/assess/templates/contract_downloads.html
https://digital.dclg.gov.uk/jira/secure/RapidBoard.jspa?rapidView=110&view=planning&selectedIssue=FS-2643&quickFilter=786&issueLimit=100
This PR fixes the alignment of the body with the banner for the following pages
- continue assessment 
- export application data 
NA
**Continue assessment page**
**Export application data page**
=> FS-2643-body-content-not-inline-with-the-banner

app/assess/data.py
We've seeded some mock assessments for NSTF, these don't have files attached as they haven't went through the full end-to-end journey, so when we are attempting to retrieve the files from AWS, we're getting an error since the keys don't exist.
This PR adds a small safeguard for that scenario, so we don't explode the page when this happens.
=> BAU: Add safe-guard for mock assessments

app/assess/data.py
When a file doesn't exist, the `Contents` isn't in the dict, this handles it better and returns an empty list.
=> BAU: Fix bug with optional files

app/assess/templates/macros/theme/question_above_answer_html.jinja2, app/assess/templates/macros/theme/question_above_href_answer_list.jinja2
This small PR fixes the styling for presentation type "free_text"
=> FS-3016-styling-fix-for-free-text-presentation-type

app/assess/routes.py, app/assess/templates/macros/scores_justification.html, app/assess/templates/score.html, config/envs/development.py, tests/test_authorisation.py, tests/test_routes.py
[FS-3020 Refactor explicit references to COF in assessment code to general fund](https://digital.dclg.gov.uk/jira/browse/FS-3020)
Removed references to COF and Fixed issue with old community fund displaying on the sub criteria page
Got to the sub criteria page for night shelter and make sure that it banner says Night Shelter
=> FS-3020 Remove references to cof

app/assess/data.py, app/assess/helpers.py, app/assess/models/flag.py, app/assess/routes.py, app/assess/templates/assessor_tasklist.html, app/assess/templates/continue_assessment.html, app/assess/templates/flag_application.html, app/assess/templates/macros/assessment_flag.html, app/assess/templates/macros/flag_history.html, app/assess/templates/resolve_flag.html, config/envs/default.py, config/envs/development.py, tests/test_authorisation.py, tests/test_jinja_macros.py, tests/test_routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2771
https://digital.dclg.gov.uk/jira/browse/FS-2664
- Added Flag history dropdown in application view page
- Continue assessment page duplicated with [design ](https://fsd-pre-award.herokuapp.com/s39-assessment/40-restart-assessment)
- Remove duplicated code of displaying multiple sections
- Set `DEBUG_USER_ON =TRUE` for development mode
This task relies on schema changes from [FS-3024](https://digital.dclg.gov.uk/jira/browse/FS-3024).(which is in progress)
To test this on localhost using mock data, set the `application_id` to your local application [here](https://github.com/communitiesuk/funding-service-design-assessment/blob/a64633d5fb8680864ef0485867b3a1783ea7e7c2/app/assess/data.py#L367)
=> Fs 2664 display flag history

app/assess/auth/validation.py, app/assess/data.py, config/envs/development.py
Issue:
`users_result` is a dictionary, and we were previously using it as a single object - this should fix the issues we are seeing on assessment at the moment, an oversight on my part.
=> BAU: Fix bulk accounts functionality

app/assess/data.py
- Instead of getting roles by using the key `[key]` - we instead use `.get()` with a default of an empty string
- This can happen if a user is un-assigned all their roles, but had left comments/scores/flags etc in the past
=> BAU: Change dict to .get so we safely retrieve roles

app/assess/templates/components/application_overviews_table_cof.html
On line 44-46, we have a search button shown for all.  But we also had this block showing one for non-assessors, this means they see two search buttons at the moment.  This PR removes the extra one for non-assessors, as we now have a search button for all.
=> BAU: Remove duplicate search button for commenters

app/assess/data.py, app/assess/models/ui/applicants_response.py, app/assess/routes.py, app/assess/templates/components/application_overviews_table_cof.html, app/aws.py, tests/test_applicators_response.py, tests/test_aws.py, tests/test_export.py
- Quote file keys when from client side upload component
- Unquote and pull files from amazon S3 when downloaded
- Move tests & add coverage
---
=> FS-3037: Show client side upload files on export page

app/assess/data.py, app/assess/models/flag_teams.py, app/assess/routes.py, app/assess/templates/assessor_tasklist.html, app/assess/templates/flag_application.html, app/assess/templates/macros/assessment_completion.html, app/assess/templates/macros/flag_history.html, tests/test_jinja_macros.py
https://dluhcdigital.atlassian.net/browse/FS-3143
https://dluhcdigital.atlassian.net/browse/FS-3141
https://dluhcdigital.atlassian.net/browse/FS-3142
- Fixed duplicated teams tab in flag history
- Unit tests and other appropriate tests updated
- `flag_teams.py` is a brief concept. Need to rework in future
**Before fix**
**After fix**
=> fixed duplicated teams tab in flag history

app/assess/display_value_mappings.py, app/assess/helpers.py, app/assess/routes.py, app/assess/templates/assessor_tasklist.html, app/assess/templates/components/header.html, app/assess/templates/macros/banner_summary.html, app/assess/templates/macros/flag_history.html, tests/conftest.py, tests/test_jinja_macros.py
https://dluhcdigital.atlassian.net/browse/FS-2776
- Added assessment status in the blue banner (`Not started`, `In progress`, `Qa completed`,  `Assessment completed`)
- Flag status shows as when available(`Multiple flags to resolve`, `Flagged for [TeamA]`, `Stopped`) 
- Unit tests and other appropriate tests are updated
=> Fs 2776 display assessment status

app/assess/templates/macros/theme/question_above_answer_html.jinja2
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?view=detail&selectedIssue=FS-3140
This PR fixes the spacing issue in the **targeted criteria theme** answer
=> FS-3140-no-spacing-in-targeted-criteria-theme

app/assess/data.py, app/assess/models/fund.py, app/assess/routes.py, app/assess/templates/all_uploaded_documents.html, app/assess/templates/assessor_tasklist.html, app/assess/templates/components/header.html, config/envs/default.py, tests/test_helpers.py
- Adds a new psuedo-theme, "all_uploaded_documents"
- This acts as a theme, but instead just gives all answers with documents
- No comments should be shown on this page
- You can not score this page
---
- Deploy this branch, or make it available somewhere
- Go to a COF application
- Observe the new section "All uploaded documents"
- You can click and observe answers, and download as usual
- You can not comment or score this section/theme
- https://github.com/communitiesuk/funding-service-design-assessment-store/pull/227
- https://github.com/communitiesuk/funding-service-design-fund-store/pull/100
=> FS-3184: Add "All uploaded documents" functionality

app/assess/templates/macros/banner_summary.html
https://dluhcdigital.atlassian.net/browse/FS-3179
Commenters will no longer see the assessment statement to match the prototype 
Have only the commenter role and see that the assessment status no longer appears
=> FS-3179 - Status is now hidden from commenters to match the prototype.

app/assess/templates/assessor_tasklist.html, app/assess/templates/macros/assessment_flag.html, tests/api_data/test_data.py, tests/test_jinja_macros.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3128
https://dluhcdigital.atlassian.net/browse/FS-3129
- Implemented flag banners for resolve, continue & stopped status
- Unit tests and other appropriate tests added or updated
Design references:
https://fsd-pre-award.herokuapp.com/s39-assessment/30-history-stopped
https://fsd-pre-award.herokuapp.com/s39-assessment/40-history-restart
https://fsd-pre-award.herokuapp.com/s39-assessment/20-history-resolved#s26-team-allocation-2
=> Fs 3128 flag banners for resolve stopped continue

app/assess/templates/flag_application.html
https://dluhcdigital.atlassian.net/browse/FS-3102
Checkbox will no longer remove the selected entries when there is a validation error
- Click flag application
- Select form sections to flag but leave the reason got flagging box empty to cause an error
- See that selected checkboxs have remained selected
=> Checkbox no longer wipes when a error occurs

app/create_app.py, app/default/routes.py, app/templates/403.html
- Add page for 403 forbidden, since it's now a common use case
- If someone without a Wales role is linked a Wales application, they may see a 403, for example
- Also if someone without a COF role is linked a COF application, they may see a 403
=> BAU: Add 403 forbidden template and handler

app/assess/templates/assessor_dashboard.html
FS-3233: Flag application COF - Applications with no allocation team assigned displays separate metrics
Fixed bug where old data, so applications that were flagged without a team allocation, would render a stats box with the team name reading as None. Now only renders if team_name is truthy
=> Makes sure valid team_name is available before rendering

app/assess/models/ui/applicants_response.py
https://dluhcdigital.atlassian.net/browse/FS-3162
Adding a fix for the how is you organisation classified. Also added comment to explain why the if is there.
Go to the organisation type section of an application that has the answer none selected. You should now see, Non of these as the answer
=> FS-3162 Fix for the org type question

app/assess/templates/macros/assessment_flag.html, app/assess/templates/macros/flag_history.html
https://dluhcdigital.atlassian.net/browse/FS-3240
Fixed the below sentry error
https://funding-service-design-team-dl.sentry.io/issues/4325904007/?alert_rule_id=13274838&alert_type=issue&project=4504418515550208&referrer=slack
Display 'N/A' when fullname not available in user accounts
=> Display 'N/A' when fullname not available in flagging

app/assess/data.py, tests/test_tags.py
- Sometimes the endpoint returns 204, so we should check `.ok` vs only `200`
https://www.geeksforgeeks.org/response-ok-python-requests/
https://communities-govuk.slack.com/archives/C02PHBER287/p1689941384490099
=> BAU: Fix red herring, check .ok vs 200 only

app/assess/routes.py
https://dluhcdigital.atlassian.net/browse/FS-3021
Disable flag button in sub-criteria page
=> Fs-3021 dont display flag button in scoring page

app/assess/templates/assessor_tasklist.html, config/envs/development.py
Ticket ref pending - fixing bug where general assessors (not leads) are unable to see the change tags/add tags button.
User does not have lead assessor for NSTF, but can see the change tags link now.
=> allowing assessors to set tags

app/assess/helpers.py, tests/api_data/test_data.py, tests/conftest.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3269
Current implementation makes multiple API calls to tagging endpoint for every application which caused the performance issues on assessment dashboard. 
- Tags are now retrieved with single API `application overviews endpoint`(no need to make separate API call to fetch tags) to improve the performance
- updated the mock data & unit tests
Also check the PR https://github.com/communitiesuk/funding-service-design-assessment-store/pull/261
=> Improve performance of assessment_dashboard

app/assess/helpers.py, app/assess/models/file_factory.py, app/assess/routes.py, app/assess/templates/contract_downloads.html, app/pdf/full_application.py
- Adds all file types to the UI on the export page
- Uses existing `format_answers` function on answers on csv/pdf
=> FS-3235: Format answers for csv/pdf & expose "pdf" on UI

app/assess/templates/assessor_dashboard.html
This tiny PR fixes the margin issue on the assessment dashboard page
=> bug-fix/FS-3333-margin-issue-with-assessment-dashboard

app/templates/403.html
Fixes issue with building the help link on the 403 error page, as per this Sentry alert in prod: https://funding-service-design-team-dl.sentry.io/issues/4412243251/?alert_rule_id=13274842&alert_type=issue&project=4504418515550208&referrer=slack
=> fixing help link on 403 page

app/blueprints/assessments/templates/assessor_dashboard.html, app/blueprints/assessments/templates/macros/section_element.html, app/static/src/styles/govuk-overrides.css, app/templates/macros/banner_summary.html, app/templates/macros/theme/question_above_answer.jinja2, app/templates/macros/theme/question_above_answer_html.jinja2, app/templates/macros/theme/question_above_href_answer.jinja2, app/templates/macros/theme/question_above_href_answer_list.jinja2, app/templates/macros/theme/question_heading.jinja2, tests/test_jinja_macros.py
- Use list instead of table for unscored sections
- Change some heading to paragraph tags for structured hierarchy
- Change theme answers to h4 as they come after h3
Addresses pages 17-30:
- [DAC Accessibility Report WCAG 2.1 - DLUHC Community ownership fund assessment - 08-02-23 - Final.pdf](https://github.com/communitiesuk/funding-service-design-assessment/files/12550892/DAC.Accessibility.Report.WCAG.2.1.-.DLUHC.Community.ownership.fund.assessment.-.08-02-23.-.Final.1.pdf)
---
=> FS-2319: Accessibility fixes

app/blueprints/scoring/templates/macros/scores_justification.html, app/blueprints/scoring/templates/macros/sub_criteria_heading.html, app/blueprints/scoring/templates/score.html, tests/test_jinja_macros.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-3450
When a user clicks on the "score the subcriteria" link, the sub-criteria title will be prefixed with the word "Score," such as "Score Engagement." This is in accordance with the new prototype.
=> FS-3450-update-scoring-page-navbar-sub-criteria-title-with-prefix-score

app/assets.py, app/templates/head.html
- Start using the template tags provided by Flask-Assets rather than hardcoded urls
- Version css/javascript bundles based on the current time, meaning each app restart will cache-bust
- Pull this branch, observe the css/javascript bundles in your `<head>` tags on any page
- Make a change to javascript/css files & ensure app has restarted (might not auto-refresh on js/css changes)
- Observe your changes to the javascript/css depending on what you changed, or view the new unique url in the `<head>` tags
=> BAU: Add version/cache-busting to javascript/css

.pre-commit-config.yaml, config/envs/default.py, copilot/environments/addons/funding-service-magic-links.yml, docs/setup.md, manifest.yml
https://dluhcdigital.atlassian.net/browse/FS-3441
- Added pre-commit 'Yelp/detect-secrets' to prevent committing of secrets to code base
- Ignore false positives by marking them with `pragma: allowlist secret`
- disabled the plugin `HexHighEntropyString` which tend to detect lot of false positives
- Add a secret/API/password to any of the file type
For eg. `API_KEY= "125fdfbdjhbj5989"`
- stage the file & commit it.
- Notice the commit is failed with errors.
=> FS-3441 added pre-commit hook yelp

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assessor_tool_dashboard.html, app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
- Adds "Export applicant information" & "Assessment Tracker Export" below rounds (even when live)
- Extracted macro & re-used in the two different places
=> FS-3438: Add round links even when live

app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
https://dluhcdigital.atlassian.net/browse/FS-3475
Make the feedback link available when round is live
=> Fs 3475 add feedback export functionality 2

app/blueprints/assessments/models/fund_summary.py, app/blueprints/assessments/routes.py, app/blueprints/authentication/auth.py, app/blueprints/authentication/validation.py, app/blueprints/flagging/helpers.py, app/blueprints/flagging/routes.py, app/blueprints/services/data_services.py, app/blueprints/services/shared_data_helpers.py, app/blueprints/shared/helpers.py, app/blueprints/tagging/routes.py, config/envs/default.py, config/envs/development.py, config/envs/test.py, tests/conftest.py, tests/test_lru_cache.py, tests/test_validation.py
https://dluhcdigital.atlassian.net/browse/FS-3339
- Implemented lru caching for fund store endpoints
- Updated & added unittests
- Cache time is set as 3600s on prod, 300s on test & 30s on dev
As initially thought, implementing LRU cache on assessment store endpoints is not the solution for performance improvement. As any caching on the assessment store endpoint will not reflect changes made by assessors on flagging or tagging immediately. So caching is added only for fund-store endpoints in this PR. Please look at the ticket comment in Jira for more information.
- Put breakpoints in the get_fund and get_round methods of fund_store
- Load the assessment frontend in a browser and check that the above breakpoints don't get hit except on the first retrieval of a session (ie the frontend has …
=> FS-3339 added lru cache for fund store endpoints

app/blueprints/assessments/models/fund_summary.py
- `export_href` was nested in a tuple which was causing the URL to fail on the front-end
- I had just found this so thought I'd fix it while I was there
=> BAU: Remove unnecessary tuple

app/blueprints/assessments/helpers.py
https://dluhcdigital.atlassian.net/browse/FS-3473
Minor bug fix - display team flag stats on banner
=> FS-3473 fix bug in `get_team_flag_stats` function

app/blueprints/services/models/fund.py
CYP config - fund type
https://dluhcdigital.atlassian.net/browse/FS-3651
=> add cyp fund type config

app/blueprints/assessments/models/applicants_response.py
https://dluhcdigital.atlassian.net/browse/FS-3699
Optional UkAddressFields will now say not supplied when no answer is given
Find an application with an optional address filed and leave it blank. Should now show not supplied on frontend
=> FS-3699 Fix for not supplied if address is None

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/macros/comments.html, app/blueprints/assessments/templates/macros/comments_box.html, app/blueprints/assessments/templates/macros/comments_edit_box.html, app/blueprints/assessments/templates/sub_criteria.html, app/blueprints/scoring/templates/macros/comments_summary.html, app/blueprints/services/data_services.py, app/blueprints/services/models/comment.py, tests/api_data/test_data.py, tests/test_authorisation.py
https://dluhcdigital.atlassian.net/browse/FS-3705
Added "Edit comment" button for the comment owner
Linked [PR](https://github.com/communitiesuk/funding-service-design-assessment-store/pull/342)
=> Fs 3705 assessor comment editing

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assessor_tool_dashboard.html, app/blueprints/assessments/templates/comments_history.html, app/blueprints/assessments/templates/macros/comments.html, app/blueprints/services/data_services.py, tests/test_authorisation.py
https://dluhcdigital.atlassian.net/browse/FS-3731
* Added `See History` button (available for comment owner & other assessor role users when history is available  )
* `See History` is available for all roles (`Commenter`, `Assessors` & `Lead Assessors`)
=> Fs 3731 add comment history

app/blueprints/assessments/routes.py
https://dluhcdigital.atlassian.net/browse/FS-3758
fix column sorting for `publish_datasets` column in DPIF when has `None` values
=> FS-3758 fix column sorting publish_datasets DPIF

app/blueprints/assessments/templates/assessor_tasklist.html, app/templates/components/header.html, app/templates/macros/banner_summary.html, tests/test_jinja_macros.py
- DPIF doesn't have total funding requested, so we should hide it on assessment front-end
- I was thinking of putting this in fund-store, but its assessment specific, so figured have it here
---
- Check out branch, check DPIF assessment on assessment front-end
- Check other fund assessment, observe it still shows properly
- Unit tests also updated accordingly
=> FS-3752: Hide total funding requested for DPIF

app/blueprints/assessments/templates/activity_trail.html
set-page-heading/FS-3685-view-assessment-activity-history-for-an-application
=> set-page-heading/FS-3685-view-assessment-activity-history-for-an-application

app/blueprints/scoring/templates/macros/scores_justification.html, app/blueprints/scoring/templates/score.html
https://dluhcdigital.atlassian.net/browse/FS-3842
Fixing a issue that caused the score history to no longer display
Score and then rescore a sub criteria and see if the history displays
=> FS-3842 - Score history not displaying bug fix

app/error_handlers.py, app/templates/maintenance.html, config/envs/default.py, create_app.py, tests/conftest.py, tests/test_maintenance.py
https://dluhcdigital.atlassian.net/browse/FS-3804
Added maintenance mode var in config, if enabled `Service unavailable` page is displayed on all routes
set the var `MAINTENANCE_MODE` to True and visit any assessment route page. Observe the maintenance page being displayed
=> FS-3804 add maintainence route

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/activity_trail.html, app/blueprints/assessments/templates/all_uploaded_documents.html, app/blueprints/assessments/templates/mark_qa_complete.html, app/blueprints/flagging/helpers.py, app/blueprints/flagging/templates/continue_assessment.html, app/blueprints/flagging/templates/resolve_flag.html, app/blueprints/tagging/routes.py, app/blueprints/tagging/templates/create_tag.html, app/blueprints/tagging/templates/deactivate_tag.html, app/blueprints/tagging/templates/edit_tag.html, app/blueprints/tagging/templates/manage_tags.html, app/blueprints/tagging/templates/reactivate_tag.html
Added downtime banner to pages missing it
Check the downtime banner is in all pages on assessment
=> Added downtime banner to pages missed

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/activity_trail.html
https://dluhcdigital.atlassian.net/browse/FS-3834
display assessment status (same logic from the assessment list page) in the activity trail page
**Scenario** : Flagged
**Scenario**: Not started
=> FS-3834 display assessment status in activity page

app/blueprints/assessments/models/fund_summary.py, app/blueprints/authentication/validation.py, tests/test_validation.py
Updated the validation on viewing applications in assessment to allow viewing them before the round has closed
- Setup EOI so the round is open and so you are within the assessment start/end dates. You will need to set an assessment_start date, so may need to run the data import script on latest fund store.
- Set the env var `FORCE_OPEN_ALL_LIVE_ASSESSMENT_ROUNDS` to `False`
- Navigate to the assessment tool landing page
- You should be able to 'view all active assessments' for EOI
=> FS-4219 Enabling assessment view

app/blueprints/assessments/templates/assessor_tasklist.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4164
Display button Export application data on the assessor task list page when a lead assessor is looged in to the tasklist page
=> FS-4164-display-export-application-data-button-for-cofeoi

app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
https://dluhcdigital.atlassian.net/browse/FS-4153
Adding if for EOI so it only shows applications received 
Check the cof EOI fund
=> FS-4153 Adding if for EOI metrics

app/blueprints/assessments/models/file_factory.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4150
Display round name next to the fund name on a text file
=> FS-4150-display-round-name-along-with-fund-name-to-the-text-file

app/blueprints/assessments/templates/macros/fund_dashboard_summary.html
Fixed bug - show `View all submited applications` link for COF-EOI
=> BAU: show submited application link EOI

app/blueprints/assessments/helpers.py, app/blueprints/assessments/models/file_factory.py, tests/test_helpers.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4235
add round title next to the fund name for csv export file
anges
=> FS-4235-round-title-not-displaying-on-application-data-csv-extract

app/blueprints/services/models/fund.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4283
Some of the funds in assessment are appearing as allocative funds, we currently have no allocative and all should be competitive.
Update the funds in assessment that are listed as allocative to be competitive
=>  FS-4283-update-funds-in-assessment-to-be-competitive

app/blueprints/assessments/templates/macros/fund_dashboard_summary.html, tests/test_jinja_macros.py
Updated link display to check whether assessment is open, not whether application has closed for the 'Export Assessment Tracker'
=> fs-4303 fixing links

app/blueprints/assessments/helpers.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4300
welsh translation for cy applications:
True/ Yes - "Oes"
False/ No - "Nac Oes"
English "Export application information"
Welsh "Export application information"
=>  FS-4300-welsh-translation-for-bool-values

config/themes_mapping.py
https://dluhcdigital.atlassian.net/browse/FFE-266
- Auction-costs removed from themes mapping for HSRA
=> FS-4413: HSRA application text updates

app/blueprints/assessments/templates/macros/section_element.html
https://dluhcdigital.atlassian.net/browse/FS-4389
- "Declaration" added in section caption condition
=> FS-4389: Declaration caption should display for Declaration as well as Declarations section

config/themes_mapping.py
https://dluhcdigital.atlassian.net/browse/FS-4452
- fund_round_short_name updated
- Visit the "View entire application" page and verify it works
=> FS-4389: Bug related to view entire application fixed

app/blueprints/services/aws.py, config/envs/default.py, config/envs/dev.py, config/envs/production.py, config/envs/test.py
VCAP services is specific to PaaS, so can be safely removed post-PaaS migration.
Tests should pass
Redis connection should still work
=> BAU: Remove VCAP specific config

app/blueprints/assessments/helpers.py, app/blueprints/assessments/routes.py
A quick fix for backwards compatibility where application overviews may not contain user association data.
=> Handle application overviews that don't have user associations

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/fund_dashboard.html, app/blueprints/assessments/templates/macros/application_overviews_table_all.html, app/blueprints/assessments/templates/macros/filter_options_all.html, config/display_value_mappings.py, tests/conftest.py, tests/test_maintenance.py, tests/test_routes.py
Drop down filter should include 'Not assigned' option to view applications that have not been assigned yet. 
This also includes a bug fix: when using the 'clear search' link, the view now remains on the current tab rather than switching to 'all applications'.
Test the UI to ensure filtering works.
=> Add filter option not assigned to view unassigned applications

app/blueprints/assessments/forms/assignment_forms.py, app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assessor_type.html, app/blueprints/assessments/templates/assign_assessments.html, app/blueprints/assessments/templates/assignment_overview.html, app/blueprints/assessments/templates/fund_dashboard.html, app/blueprints/assessments/templates/macros/application_overviews_table_all.html, app/blueprints/assessments/templates/macros/filter_options_all.html, app/blueprints/assessments/templates/macros/team_dashboard_header.html, app/blueprints/assessments/templates/select_assessor.html, app/blueprints/services/data_services.py, app/blueprints/shared/filters.py, app/static/src/js/helpers.js, app/static/src/styles/govuk-overrides.css, config/envs/default.py, config/envs/development.py, config/envs/test.py, create_app.py, tests/conftest.py, tests/test_assignment.py, tests/test_routes.py
This PR covers several views to enable lead assessors to assign assessments to other lead or general assessors. Things to note:
- The actual assignments are only created after submission on the final page (assignment_overview). The views prior to this only store user selections via hidden input fields (persistent storage is not used until the final submission). 
- This development only covers the ability to assign users to assessments (un-assignment will be covered in another ticket).
- The search bar and 'Team' column are no longer needed. The optional comment field will be covered in another ticket.
Follow the figma flow in the ticket to test the workflow and views.
=> FS-3987 assign user assessment

app/blueprints/assessments/forms/assignment_forms.py, app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assessor_type.html, app/blueprints/assessments/templates/assign_assessments.html, app/blueprints/assessments/templates/macros/application_overviews_table_all.html, app/blueprints/assessments/templates/select_assessor.html, tests/test_assignment.py
Follow on from https://github.com/communitiesuk/funding-service-design-assessment/pull/670/files.
An update in the ticket requires that only one assessment can be selected for assignment at a time. This PR updates the validation handling and error messaging. 
=> Only allow a single assessment to be selected for assignment

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/sub_criteria.html, app/blueprints/services/models/assessor_task_list.py, tests/api_data/test_data.py, tests/test_shared_helpers.py
On the application detail page (task list into individual sections), allow moving between section detail pages with a next/ previous pagination component.
We use the govuk design system `pagination` component which is supported by our pinned version of the design system and the jinja component library used.
The `state` dictionary which is consumed by every detail route describes the application and the assessors progress through it, as it already loaded information on all of the sections this seemed like a good place to add a utility for pagination. This utility can then also be used anywhere future tickets may need to move forwards and backwards between sections.
This learns from the functionality but deviates from the implementation of a [work in progress …
=> FS-4082 Add pagination logic for sections on an application

app/blueprints/services/data_services.py
Quick fix for get_application_assignments to return empty list instead of None. 
Also extend assign_user_to_assessment to be able to un-assign assessments.
=> Update get_application_assignments to default to empty list

app/blueprints/assessments/templates/sub_criteria.html, app/blueprints/scoring/routes.py, app/blueprints/scoring/templates/score.html, app/blueprints/services/models/assessor_task_list.py, app/templates/components/sub_section_pagination.html, tests/test_shared_helpers.py
Uniformly show the sub-section pagination component on the "scoring" page (either if the sub-section has already been scored or is it yet to be scored).
This would navigate to the default sub-section page (the top link on the left hand nav) to keep it consistent with the other pagination.
The sub section pagination is shared by the `scores` and `assessments` blueprints. As it relies on the a consistent helper model move it into a component that can be included by those separate templates.
The scoring sub-page with pagination before a score has been submitted.
The scoring sub-page with pagination after a score has been submitted.
=> FS-4082 Show pagination uniformly on the scoring page

app/blueprints/assessments/forms/assignment_forms.py, app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assignment_overview.html, app/blueprints/services/data_services.py, config/envs/unit_test.py, tests/test_assignment.py
Lead assessors can now un-assign assessors who have been assigned applications. It is possible to assign and unassign different users to the same application in one go.
=> Implement ability to unassign assessors from applications

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assignment_overview.html, tests/test_assignment.py
This PR contains two fixes for the assignment overview page:
- Added missing ul tags for list
- Add checks to ensure user has permissions to make assignments for selected assessors / assessments.
=> Assignment overview fixes

app/blueprints/assessments/templates/fund_dashboard.html, app/blueprints/assessments/templates/macros/team_dashboard_header.html, app/static/src/styles/govuk-overrides.css, app/templates/macros/logout_partial.html
https://dluhcdigital.atlassian.net/browse/FS-4546
- Replaced anchor tag with form button having csrf token
- Button styled as link to be consistent with design
- Bugfix, "Log out" button was not working on fund_dashboard
- Login to assessment and verify /sso/logout are logging user out as expected
Assessment Logout:
=> Fs 4546 post logout

app/blueprints/assessments/forms/assignment_forms.py, app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assessor_comments.html, app/blueprints/assessments/templates/assignment_overview.html, app/blueprints/services/data_services.py, app/static/src/js/helpers.js, tests/test_assignment.py
This PR covers the page and functionality to allow users to specify a custom message for the email notifications that are sent when assignments are made. It is dependent on changes in the assessment store and notification. 
There are 3 scenarios to check in the work allocation flow for both assignment and unassignment :
- No messages are provided 
- Message to all assignees is provided
- Messages to individual assignees are provided 
An email should be sent in all cases, and where a message is provided, it should also appear in the email
=> FS 4579 Email comments for assessors

app/blueprints/assessments/routes.py, app/blueprints/assessments/templates/assignment_overview.html
Minor UI fixes for FS-4579 including:
- Formatting of the 'Add messages button'
- Missing hint text to indicate whether or not messages have been added in the overview screen
- Display status of assessments selected for assignment
=> FS-4579: Fix layout issues and display status of assessments

app/blueprints/assessments/models/round_summary.py, tests/test_round_summaries.py
The stats for COF-EOI in the assessor_tool_dashboard were not displaying when the applications were closed. This fix corrects the logic in create_round_summaries to fix that. 
=> Populate stats for cof eoi when applications are closed

app/blueprints/assessments/templates/activity_trail.html, app/blueprints/assessments/templates/assessor_tasklist.html, app/blueprints/assessments/templates/view_entire_application.html, app/blueprints/services/data_services.py, app/blueprints/services/models/assessor_task_list.py, app/blueprints/services/models/fund.py, app/blueprints/services/shared_data_helpers.py, app/templates/components/header.html, app/templates/macros/banner_summary.html, tests/conftest.py, tests/test_data_operations.py, tests/test_jinja_macros.py
Fixing anything in assessment with hard coded references to EOI - FS-4674
- Remove hard coded list of fund short codes that was determining what fund_type to use. Changed this to retrieve the list of all fund codes from fund-store so new funds will just work. (When we add `fund_type` as a specific configuration value on fund store, this needs changing to use that)
- Updating `banner_summary` macro to use the existing configuration value 'is_expression_of_interest' from the round rather than `if short_name=='COF-EOI':`
=> Removing list of fund short codes

app/blueprints/shared/routes.py, app/blueprints/shared/templates/index.html, app/templates/maintenance.html
The old support email was using the levellingup domain ( [fsd.support@levellingup.gov.uk](mailto:fsd.support@levellingup.gov.uk) ). This has been updated to fundingservice.support@communities.gov.uk
=> Update support email to communities from levellingup

app/blueprints/services/models/fund.py
This adds a suffix to the name of funds with the `funding_type` property "EOI".
Note that the fund name is used in many places in the assessment tool so for now this just sets the suffix in the data model, ideally this should be a presentation layer (template) concern and be done by jinja based on the funds properties. This however does the job.
Committing for opinions and consensus.
=> FS-4647 Visually differentiate expresssion of interest funds

copilot/fsd-assessment/manifest.yml
This will help us migrate from the "microservice"-y application-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-122
=> BAU: Move application store api host to AWS parameter store secret

config/themes_mapping.py
Adding themes configuration for the crash test dummy fund to enable the 'view whole application' page in assessment
=> adding theme list for ctdf

copilot/fsd-assessment/manifest.yml
This is because the `recreate` deployment method leads to downtime, which can cause tests to flake. It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling
=> Turn off recreate deployments in test env
